# Generated by Django 6.0.4 on 2026-07-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipent', models.EmailField(max_length=254)),
                ('purpose', models.TextField()),
                ('tone', models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('FRIENDLY AND CONVERSATIONAL', 'Friendly and Conversational'), ('EMPATHETIC AND SUPPORTIVE', 'Empathetic and Supportive'), ('HUMOUROUS AND PLAYFUL', 'Humorous and Playful'), ('DIRECT AND ASSERTIVE', 'Direct and Assertive')], max_length=50)),
                ('length', models.PositiveIntegerField()),
                ('output', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
