# Generated by Django 6.0.4 on 2026-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email_db_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_db',
            name='recipent',
            field=models.CharField(max_length=200),
        ),
    ]
